In [ ]:
# In machine learning, particularly when working with libraries like scikit-learn, "fit" and "fit transform" are methods
# commonly used in the context of transformers and models.
#     Use fit when you want to compute the parameters needed for transformation or train a model.
#     Use transform  when you want to apply a previously computed transformation to new data.
#     Use fit_transform when you want to compute and apply the transformation in one step, especially when working with large datasets.

In [1]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

In [7]:
data = np.array([[1.0, 2.0, 3.0], 
                 [4.0, 5.0,6.0],
                 [7.0,8.0,9.0]])

In [4]:
scaler = MinMaxScaler()

In [6]:
data_transformed = scaler.fit_transform(data)
data_transformed

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [13]:
scaler.fit(data)
data_transformed = scaler.transform(data)

In [15]:
print('Original data\n', data)
print('Transformed data\n', data_transformed)
print('Transformed data shape\n', data_transformed.shape)

Original data
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Transformed data
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
Transformed data shape
 (3, 3)
